# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 07:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('time', models.DateTimeField(default=datetime.datetime(2016, 2, 20, 7, 10, 59, 386380))),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('paragraphNumber', models.IntegerField(default=1)),
                ('time', models.DateTimeField(default=datetime.datetime(2016, 2, 20, 7, 10, 59, 387144))),
                ('blog', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.Blog')),
            ],
        ),
    ]
