# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 11:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.DateTimeField(default=datetime.datetime(2016, 2, 17, 17, 18, 34, 84000))),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='paragraphs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 17, 17, 18, 34, 84000)),
        ),
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Blog'),
        ),
    ]
