# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 07:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160218_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='paragraphs',
        ),
        migrations.AlterField(
            model_name='blog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 18, 13, 17, 32, 686000)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 18, 13, 17, 32, 688000)),
        ),
    ]
