# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 09:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160218_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='paragraphNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 18, 14, 54, 43, 630000)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 18, 14, 54, 43, 632000)),
        ),
    ]
